// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace OrderBookModuleScssNamespace {
    export interface IOrderBookModuleScss {
        orderBookContainer: string;
    }
}

declare const OrderBookModuleScssModule: OrderBookModuleScssNamespace.IOrderBookModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: OrderBookModuleScssNamespace.IOrderBookModuleScss;
};

export = OrderBookModuleScssModule;
