// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace OrderBookHeaderModuleScssNamespace {
  export interface IOrderBookHeaderModuleScss {
    button: string
    header: string
    kill: string
    select: string
    toggle: string
  }
}

declare const OrderBookHeaderModuleScssModule: OrderBookHeaderModuleScssNamespace.IOrderBookHeaderModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: OrderBookHeaderModuleScssNamespace.IOrderBookHeaderModuleScss
}

export = OrderBookHeaderModuleScssModule
